config/routes.rb
Rails.application.routes.draw do
  resources :pets
  # get '/pets', to: 'pets#index', as: :pets

  # get '/pets/new', to: 'pets#new', as: :new_pet
  # post '/pets', to: 'pets#create'

  # get '/pets/:id', to: 'pets#show', as: :pet

  # get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet
  # patch '/pets/:id', to: 'pets#update'

  # delete '/pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  # associations
  # validations
  SPECIES = ['cat', 'dog', 'hamster', 'snake', 'rabbit', 'fish']
  validates :species, inclusion: { in: SPECIES }
end

# Pet::SPECIES

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  # '/pets'
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    # just for the form
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1638</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: @pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
  <%= f.label :species %>
  <%= f.select :species, Pet::SPECIES, {}, class: 'form-select' %>
  <%= f.label :found_on %>
  <%= f.date_field :found_on, class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <h1>Update Pet</h1>
  <%= render 'pets/form' %>
</div>

app/views/pets/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h1>Found Pets</h1>
    <%= link_to 'Add Pet', new_pet_path, class: 'btn btn-success'  %>
  </div>
  <% @pets.each do |pet| %>
    <h3><%= link_to pet.name, pet_path(pet), class: 'text-decoration-none' %></h3>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="container">
  <h1>Add Pet</h1>
  <%= render 'pets/form' %>
</div>

app/views/pets/show.html.erb
<div class="container">
  <h1><%= @pet.name %></h1>
  <p><%= @pet.species %></p>
  <p><%= @pet.address %></p>
  <p><%= @pet.found_on.strftime('%A, %b %d') %></p>
  <%= link_to 'All pets', pets_path, class: 'btn btn-light'  %>
  <p>
    <%= link_to pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Remove #{@pet.name}?" } do %>
      <i class="fa-regular fa-circle-xmark"></i>
    <% end %>
  </p>
</div>